### ISSUE TITLE
Back button on event's page is occluded by the topbar

### ISSUE THREAD

**Issue by fgregg** [datamade/nyc-council-councilmatic#59] opened 2017-12-11 20:56 UTC
https://nyc-council-staging.datamade.us/event/committee-on-education-9c6f4e323984/

![screenshot-2017-12-11 nyc councilmatic 2](https://user-images.githubusercontent.com/536941/33853381-6999e3be-de83-11e7-852c-172bb25dc108.png)

**Comment by reginafcompton** [comment] 2017-12-11 22:19
Duplicate of #55 - closing.

**Closed by reginafcompton** 2017-12-11 22:19 UTC
